[RtspServer]
RtspPort = 11554
ReadTimeout = 10 #s
WriteTimeout = 10 #s

[Logger]
Level = "info"
MaxSize = 500 #MB
MaxBackups = 5 #
MaxAge = 5 #day
Development = true

[RtmpServer]
RtmpPort = 1935
ReadTimeout = 10 #s
WriteTimeout = 10 #s
FlvDir = "./tmp"